# Generated by Django 5.0.6 on 2026-05-19 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la campaña')),
                ('cliente_nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('industria', models.CharField(help_text='Ej: tecnología, retail, salud, educación.', max_length=100, verbose_name='Industria')),
                ('tono', models.CharField(choices=[('profesional', 'Profesional'), ('casual', 'Casual'), ('urgente', 'Urgente'), ('inspiracional', 'Inspiracional'), ('humoristico', 'Humorístico'), ('persuasivo', 'Persuasivo')], default='profesional', max_length=20, verbose_name='Tono del mensaje')),
                ('plataforma', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('linkedin', 'LinkedIn'), ('google_ads', 'Google Ads'), ('tiktok', 'TikTok')], default='instagram', max_length=20, verbose_name='Plataforma de publicación')),
                ('prompt', models.TextField(help_text='Descripción de la campaña enviada a Gemini vía n8n.', verbose_name='Prompt de entrada')),
                ('texto_generado', models.TextField(blank=True, default='', help_text='Texto publicitario devuelto por Gemini.', verbose_name='Copy generado')),
                ('imagen_url', models.URLField(blank=True, help_text='Imagen generada por Stability AI (HU21, Sprint 4).', null=True, verbose_name='URL de imagen')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_ia', 'Pendiente IA'), ('generado', 'Generado'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], db_index=True, default='borrador', max_length=30, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('marketero', models.ForeignKey(help_text='Usuario con rol marketero que creó y gestiona esta campaña.', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Marketero')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'db_table': 'campaigns',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='idx_campaign_estado'), models.Index(fields=['marketero', 'estado'], name='idx_campaign_marketero_estado')],
            },
        ),
    ]
