# Generated by Django 5.0.6 on 2026-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_campaign_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="feedback_rechazo",
            field=models.TextField(
                blank=True,
                help_text="Motivo escrito por el cliente cuando rechaza la campaña (HU15). Null para campañas aprobadas o en otros estados.",
                null=True,
                verbose_name="Feedback de rechazo",
            ),
        ),
    ]
