# Generated by Django 5.0.6 on 2026-06-06 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_campaign_imagen_b64"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("texto_generado", models.TextField()),
                ("imagen_b64", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaigns_campaignversion",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "-version_number"],
                        name="campaigns_c_campaig_bb13fe_idx",
                    )
                ],
                "unique_together": {("campaign", "version_number")},
            },
        ),
    ]
