# Generated by Django 5.0.6 on 2026-07-06 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_campaign_fracaso_rechazos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('creditos', models.PositiveIntegerField()),
                ('estado', models.CharField(default='aprobado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_creditos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaigns_creditpurchase',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
