# Generated by Django 5.0.6 on 2026-10-02 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_creditpurchase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('voz', 'Voz'), ('formulario', 'Formulario')], default='voz', max_length=20)),
                ('transcripcion', models.TextField(help_text='Texto dictado o escrito por el usuario. Nunca audio.')),
                ('campos_interpretados', models.JSONField(default=dict, help_text='Campos que propuso la IA, ya validados contra el dominio. No se modifican.')),
                ('campos_finales', models.JSONField(default=dict, help_text='Campos tras las correcciones del usuario; con ellos se crea la campaña.')),
                ('advertencias', models.JSONField(default=list, help_text='Valores que la IA propuso y el dominio no reconoce.')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('descartado', 'Descartado')], db_index=True, default='borrador', max_length=20)),
                ('modelo_ia', models.CharField(blank=True, default='', max_length=80)),
                ('uso_ia', models.JSONField(blank=True, null=True)),
                ('interpretacion_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('confirmado_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intencion', to='campaigns.campaign')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intenciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_intents',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'estado'], name='idx_intent_usuario_estado')],
            },
        ),
    ]
