# Generated by Django 5.0.6 on 2026-10-07 01:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_instagramaccount_instagramauthorization_and_more'),
        ('campaigns', '0013_campaign_plataformas'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=150)),
                ('campaign_version', models.IntegerField()),
                ('caption', models.TextField()),
                ('image_jpeg', models.TextField()),
                ('image_ticket', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('image_expires_at', models.DateTimeField()),
                ('status', models.CharField(default='preparing', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=64)),
                ('media_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.instagramaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='instagrampublication',
            constraint=models.UniqueConstraint(fields=('campaign', 'instagram_user_id', 'campaign_version'), name='unique_instagram_publication'),
        ),
    ]
