# Generated by Django 5.0.6 on 2026-10-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_facebookauthorization_facebookpage_and_more'),
        ('campaigns', '0014_instagrampublication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_id', models.CharField(max_length=64)),
                ('page_name', models.CharField(max_length=255)),
                ('campaign_version', models.IntegerField()),
                ('caption', models.TextField()),
                ('image_jpeg', models.TextField()),
                ('status', models.CharField(default='publishing', max_length=20)),
                ('photo_id', models.CharField(blank=True, max_length=64)),
                ('post_id', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.facebookpage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='facebookpublication',
            constraint=models.UniqueConstraint(fields=('campaign', 'facebook_page_id', 'campaign_version'), name='unique_facebook_publication'),
        ),
    ]
