# Generated by Django 5.0.6 on 2026-10-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_xaccount_xauthorization_and_more'),
        ('campaigns', '0015_facebookpublication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=150)),
                ('campaign_version', models.IntegerField()),
                ('caption', models.TextField()),
                ('image_jpeg', models.TextField()),
                ('status', models.CharField(default='preparing', max_length=20)),
                ('media_id', models.CharField(blank=True, max_length=64)),
                ('post_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.xaccount')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
        migrations.AddConstraint(
            model_name='xpublication',
            constraint=models.UniqueConstraint(fields=('campaign', 'x_user_id', 'campaign_version'), name='unique_x_publication'),
        ),
    ]
