# Generated by Django 5.0.6 on 2026-10-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_xpublication_xpublication_unique_x_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='textos_por_plataforma',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaignversion',
            name='textos_por_plataforma',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
