# Generated by Django 5.0.6 on 2026-10-06 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0013_campaign_intent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('cuenta_id', models.CharField(help_text='ID en Meta: página de Facebook o cuenta de Instagram profesional.', max_length=64)),
                ('cuenta_nombre', models.CharField(help_text='Nombre de la página o @usuario.', max_length=150)),
                ('pagina_id', models.CharField(help_text='Página de Facebook a la que pertenece el token (la misma en Instagram vinculado).', max_length=64)),
                ('token_cifrado', models.TextField(blank=True, default='', help_text='Token de página cifrado. Nunca se expone.')),
                ('token_expira_at', models.DateTimeField(blank=True, help_text='Null: el token de página no informa vencimiento.', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('desconectada', 'Desconectada')], db_index=True, default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(help_text='Quien autorizó la cuenta (cliente dueño o marketero que la administra).', on_delete=django.db.models.deletion.CASCADE, related_name='conexiones_sociales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_connections',
                'ordering': ['red', 'cuenta_nombre'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=20)),
                ('cuenta_nombre', models.CharField(help_text='Copia para mostrar aunque la cuenta se desconecte.', max_length=150)),
                ('estado', models.CharField(choices=[('esperando_aprobacion', 'Esperando aprobación'), ('publicando', 'Publicando'), ('publicado', 'Publicado'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], db_index=True, default='esperando_aprobacion', max_length=30)),
                ('copy_aprobado', models.TextField(blank=True, default='')),
                ('imagen_aprobada_b64', models.TextField(blank=True, null=True)),
                ('version_aprobada', models.IntegerField(blank=True, help_text='Campaign.version que aprobó el cliente.', null=True)),
                ('contenedor_id', models.CharField(blank=True, default='', max_length=64)),
                ('externo_id', models.CharField(blank=True, default='', max_length=64)),
                ('permalink', models.URLField(blank=True, default='', max_length=500)),
                ('error', models.TextField(blank=True, default='')),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('publicado_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to='campaigns.campaign')),
                ('solicitada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('conexion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publicaciones', to='social.socialconnection')),
            ],
            options={
                'db_table': 'social_publications',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.UniqueConstraint(fields=('usuario', 'red', 'cuenta_id'), name='uniq_conexion_usuario_red_cuenta'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['campaign', 'estado'], name='idx_publicacion_campana_estado'),
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('campaign', 'conexion'), name='uniq_publicacion_campana_conexion'),
        ),
    ]
