# Generated by Django 5.0.6 on 2026-10-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_social_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me_gusta', models.IntegerField(blank=True, help_text='Likes en Instagram; reacciones en Facebook.', null=True)),
                ('comentarios', models.IntegerField(blank=True, null=True)),
                ('compartidos', models.IntegerField(blank=True, null=True)),
                ('guardados', models.IntegerField(blank=True, help_text='Solo Instagram.', null=True)),
                ('alcance', models.IntegerField(blank=True, help_text='Cuentas únicas que vieron la publicación.', null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('interacciones', models.IntegerField(blank=True, help_text='Total de interacciones (o clics en Facebook).', null=True)),
                ('crudo', models.JSONField(blank=True, default=dict, help_text='Respuesta de Meta, para auditar.')),
                ('error', models.TextField(blank=True, default='')),
                ('obtenida_at', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='social.publication')),
            ],
            options={
                'db_table': 'social_publication_metrics',
                'ordering': ['-obtenida_at'],
                'indexes': [models.Index(fields=['publicacion', '-obtenida_at'], name='idx_metrica_pub_fecha')],
            },
        ),
    ]
