# Generated by Django 5.0.6 on 2026-05-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_disponibles',
            field=models.IntegerField(default=100, help_text='Cuota de generaciones IA restantes en el plan actual.', verbose_name='Tokens disponibles'),
        ),
    ]
