# Generated by Django 5.0.6 on 2026-10-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_instagramaccount_instagramauthorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramauthorization',
            name='return_origin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
