# Generated by Django 5.0.6 on 2026-10-07 03:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_instagramauthorization_return_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('token_version', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('return_origin', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_page_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('encrypted_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='facebookpage',
            constraint=models.UniqueConstraint(fields=('owner', 'facebook_page_id'), name='unique_owner_facebook_page'),
        ),
    ]
