# Generated by Django 5.0.6 on 2026-10-08 16:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_facebookauthorization_facebookpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_user_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=150)),
                ('encrypted_access_token', models.TextField()),
                ('encrypted_refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('encrypted_verifier', models.TextField()),
                ('token_version', models.IntegerField()),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('return_origin', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='xaccount',
            constraint=models.UniqueConstraint(fields=('owner', 'x_user_id'), name='unique_owner_x_account'),
        ),
    ]
